name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish @vscode/iconv-lite-umd
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: @vscode/iconv-lite-umd

        buildSteps:
          - script: yarn install
            displayName: Install and build

        testSteps:
          - script: yarn install
            displayName: Install and build

          - script: yarn test
            displayName: Test npm package

        publishPackage: ${{ parameters.publishPackage }}
